language: haskell
install:
  - npm install -g elm
  - elm-package install -y
before_script: 
  - elm-make --warn --output elm.js Bracket.elm
  - elm-make --yes --output test.js tests/Tests.elm
script: node test.js