module Version exposing (..) -- where 
{-| This file is auto-generated by the Python script version.py. -} 


version : String 
version = "v4.0-beta-29-gc5af812"

gitRepo : String 
gitRepo = "https://github.com/kgashok/vbracket"

