module Version exposing (..) -- where 
{-| This file is auto-generated by the Python script version.py. -} 


version : String 
version = "v4.0-beta-5-ga68f88b"

gitRepo = "https://github.com/kgashok/vbracke"

