module Version exposing (..) -- where 
{-| This file is auto-generated by the Python script version.py. -} 


version : String 
version = "v4.0-beta-13-g8c3d75f"

gitRepo : String 
gitRepo = "https://github.com/kgashok/vbracket"

